// prisma/seed/dog-training/achievements.ts
export type DogAchievementSeed = {
  id: string
  titleDe: string
  titleEn: string
  descriptionDe: string
  descriptionEn: string
  emoji: string
  conditionType: string
  conditionValue: number
  conditionMeta: string | null
  sortOrder: number
}

export const DOG_TRAINING_ACHIEVEMENTS: DogAchievementSeed[] = [
  {
    id: "first_session",
    titleDe: "Erstes Training",
    titleEn: "First Training",
    descriptionDe: "Du hast deine erste Trainingseinheit mit dem Hund protokolliert.",
    descriptionEn: "You have logged your first training session with the dog.",
    emoji: "🐾",
    conditionType: "session_count",
    conditionValue: 1,
    conditionMeta: null,
    sortOrder: 1,
  },
  {
    id: "first_skill_fluent",
    titleDe: "Erster Skill im Aufbau",
    titleEn: "First Skill Fluent",
    descriptionDe: "Einer der Skills hat das Fluency-Level erreicht.",
    descriptionEn: "One of the skills has reached the Fluency level.",
    emoji: "🌱",
    conditionType: "skill_status",
    conditionValue: 1,
    conditionMeta: "fluency",
    sortOrder: 2,
  },
  {
    id: "first_skill_proficient",
    titleDe: "Erster Skill generalisiert",
    titleEn: "First Skill Generalized",
    descriptionDe: "Einer der Skills wurde generalisiert.",
    descriptionEn: "One of the skills has been generalized.",
    emoji: "🎓",
    conditionType: "skill_status",
    conditionValue: 1,
    conditionMeta: "proficiency",
    sortOrder: 3,
  },
  {
    id: "first_skill_mastered",
    titleDe: "Erster Skill überlernt",
    titleEn: "First Skill Mastered",
    descriptionDe: "Einer der Skills hat Mastery erreicht.",
    descriptionEn: "One of the skills has reached Mastery.",
    emoji: "🏆",
    conditionType: "skill_status",
    conditionValue: 1,
    conditionMeta: "mastery",
    sortOrder: 4,
  },
  {
    id: "all_beginner_fluent",
    titleDe: "Die Basics sitzen",
    titleEn: "The Basics Are Solid",
    descriptionDe: "25 Skills sind mindestens im Aufbau-Level.",
    descriptionEn: "25 skills have reached at least Fluency level.",
    emoji: "📘",
    conditionType: "skill_status",
    conditionValue: 25,
    conditionMeta: "fluency",
    sortOrder: 5,
  },
  {
    id: "pillar_50_basic",
    titleDe: "Grundgehorsam halfway",
    titleEn: "Basic Obedience Halfway",
    descriptionDe: "Die Säule Grundgehorsam ist zu 50% gesund.",
    descriptionEn: "The Basic Obedience pillar is at 50% health.",
    emoji: "📋",
    conditionType: "pillar_health",
    conditionValue: 50,
    conditionMeta: "basic_obedience",
    sortOrder: 6,
  },
  {
    id: "pillar_90_basic",
    titleDe: "Grundgehorsam-Meister",
    titleEn: "Basic Obedience Master",
    descriptionDe: "Die Säule Grundgehorsam ist zu 90% gesund.",
    descriptionEn: "The Basic Obedience pillar is at 90% health.",
    emoji: "🥇",
    conditionType: "pillar_health",
    conditionValue: 90,
    conditionMeta: "basic_obedience",
    sortOrder: 7,
  },
  {
    id: "pillar_50_impulse",
    titleDe: "Impulskontrolle halb",
    titleEn: "Impulse Control Halfway",
    descriptionDe: "Die Säule Impulskontrolle ist zu 50% gesund.",
    descriptionEn: "The Impulse Control pillar is at 50% health.",
    emoji: "🛑",
    conditionType: "pillar_health",
    conditionValue: 50,
    conditionMeta: "impulse_control",
    sortOrder: 8,
  },
  {
    id: "pillar_50_recall",
    titleDe: "Rückruf halb",
    titleEn: "Recall Halfway",
    descriptionDe: "Die Säule Rückruf ist zu 50% gesund.",
    descriptionEn: "The Recall pillar is at 50% health.",
    emoji: "🎯",
    conditionType: "pillar_health",
    conditionValue: 50,
    conditionMeta: "recall",
    sortOrder: 9,
  },
  {
    id: "ten_sessions",
    titleDe: "Dranbleiber",
    titleEn: "Persistent",
    descriptionDe: "10 Trainings-Sessions insgesamt protokolliert.",
    descriptionEn: "Logged 10 training sessions total.",
    emoji: "🔟",
    conditionType: "session_count",
    conditionValue: 10,
    conditionMeta: null,
    sortOrder: 10,
  },
  {
    id: "fifty_sessions",
    titleDe: "Ambitioniert",
    titleEn: "Ambitious",
    descriptionDe: "50 Trainings-Sessions insgesamt protokolliert.",
    descriptionEn: "Logged 50 training sessions total.",
    emoji: "5️⃣0️⃣",
    conditionType: "session_count",
    conditionValue: 50,
    conditionMeta: null,
    sortOrder: 11,
  },
  {
    id: "hundred_sessions",
    titleDe: "Durchhaltevermögen",
    titleEn: "Endurance",
    descriptionDe: "100 Trainings-Sessions insgesamt protokolliert.",
    descriptionEn: "Logged 100 training sessions total.",
    emoji: "💯",
    conditionType: "session_count",
    conditionValue: 100,
    conditionMeta: null,
    sortOrder: 12,
  },
  {
    id: "training_streak_7",
    titleDe: "Woche der Disziplin",
    titleEn: "Week of Discipline",
    descriptionDe: "7 Tage in Folge mindestens eine Trainings-Session.",
    descriptionEn: "At least one training session for 7 consecutive days.",
    emoji: "🔥",
    conditionType: "training_streak_days",
    conditionValue: 7,
    conditionMeta: null,
    sortOrder: 13,
  },
  {
    id: "training_streak_30",
    titleDe: "Monat der Disziplin",
    titleEn: "Month of Discipline",
    descriptionDe: "30 Tage in Folge mindestens eine Trainings-Session.",
    descriptionEn: "At least one training session for 30 consecutive days.",
    emoji: "⚡",
    conditionType: "training_streak_days",
    conditionValue: 30,
    conditionMeta: null,
    sortOrder: 14,
  },
  {
    id: "team_training",
    titleDe: "Gemeinsam stark",
    titleEn: "Stronger Together",
    descriptionDe: "10 Sessions gemeinsam mit einem anderen Familienmitglied.",
    descriptionEn: "10 sessions trained together with another family member.",
    emoji: "🤝",
    conditionType: "team_session_count",
    conditionValue: 10,
    conditionMeta: null,
    sortOrder: 15,
  },
]
